version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=perkin-hoffman.at
      - LETSENCRYPT_HOST=perkin-hoffman.at
      - VIRTUAL_PORT=5000
    network_mode: bridge
  
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    depends_on: 
      - app

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=devteam@invinciblebrands.com
    network_mode: bridge
    depends_on: 
      - app

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
